apiVersion: v1
kind: LimitRange
metadata:
  name: nxs-limit-per-container
  namespace: monitoring 
spec:
 limits:
   - type: Container
     defaultRequest:
#       cpu: 50m
#       memory: 300Mi
       cpu: 100m
       memory: 500Mi
     default:
       cpu: 100m
       memory: 500Mi
#     min:
#       cpu: 50m
#       memory: 500Mi
#     max:
#       cpu: 2
#       memory: 4Gi
