#apiVersion: v1
#kind: Namespace
#metadata:
#  name: cert-manager-test
#---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cosysoft-selfsigned
#  namespace: cert-manager-test
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cosy-selfsigned-cert
#  namespace: cert-manager-test
spec:
  dnsNames:
    - '*.cosysoft.loc'
  secretName: cosy-selfsigned-cert-tls
  issuerRef:
    name: cosysoft-selfsigned
